[package]
name = "cargo-rocket-docker"
version = "0.1.0"
authors = ["Gary Ascuy <gary.ascuy@gmail.com>"]
edition = "2018"
repository = "https://github.com/DenisKolodin/cargo-docker"
description = "A cargo subcommand to create docker image from rocket project"
readme = "readme.md"
license = "MIT"

[dev-dependencies]
cargo-watch = "7.3.0"
cargo-edit = "0.6.0"
