# Build Stage
FROM rustlang/rust:nightly-alpine as builder
LABEL maintainer="{{{maintainer}}}"

WORKDIR /code
RUN apk update \
    && apk add build-base openssl-dev zlib-dev {{{packages.build}}} \
    && rm -rf /var/cache/apk/*
COPY . .
RUN cargo build --release

# Image Stage
FROM alpine:latest
LABEL maintainer="{{{maintainer}}}"

ENV ROCKET_ENV=production \
    ROCKET_ADDRESS=0.0.0.0 ROCKET_PORT=3666 \
    ROCKET_LOG=critical
{{#if packages.image}}
RUN apk update \
    && apk add {{{packages.image}}} \
    && rm -rf /var/cache/apk/*
{{/if}}
EXPOSE 3666

COPY --from=builder /code/target/release/{{{name}}} /usr/local/bin/{{{name}}}
CMD {{{name}}}
